### PR TITLE
Fix Azure integration misalignment

### PR DESCRIPTION
**Pull request by joshuaphelpsms**
fixes https://github.com/traceloop/openllmetry/issues/408

Adds:
- missing `os` import
- updates the sample code to show more traces. 
- updates the screenshot to show accurate information. The previous screenshot contained information that was not included in the sample which made it a bit confusing.

### CODE REVIEW

**Review by drewby — CHANGES_REQUESTED** [review]
I agree the screenshot should be accurate to what appears in Application Insights, but just having the single span isn't particularly interesting for a Trace visualization. Suggest we keep the previous screenshot, or a similar screenshot with multiple spans, and explain that it is an example (not the output from the tutorial). Or we update the tutorial to do a multi-step workflow.

**Comment by joshuaphelpsms** [comment]
> I agree the screenshot should be accurate to what appears in Application Insights, but just having the single span isn't particularly interesting for a Trace visualization. Suggest we keep the previous screenshot, or a similar screenshot with multiple spans, and explain that it is an example (not the output from the tutorial). Or we update the tutorial to do a multi-step workflow.

That make sense. How about something similar to the code here? https://www.traceloop.com/docs/openllmetry/tracing/annotations

**Comment by drewby** [comment]
> That make sense. How about something similar to the code here? https://www.traceloop.com/docs/openllmetry/tracing/annotations#workflows-and-tasks

Sure, that should be a bit more interesting of a visualization.

**Comment by drewby** [comment]
I like the new trace visual much better. I wonder why we are seeing "N/A" for `Type` and whether we can fix that? Perhaps @nirga knows the answer.

**Comment by nirga** [comment]
@drewby my guess is that is because we use type internal for the OpenAI span. Do you think it should be something different?

**Comment by nirga** [comment]
Hmm @drewby I thought I might knew but I actually have no idea where this N/A is coming from 🤔

**Comment by drewby** [comment]
> Hmm @drewby I thought I might knew but I actually have no idea where this N/A is coming from 🤔

I looked at this more closely. For OpenAI calls, you are setting SpanKind.Client (whereas the LLM spans are SpanKing.Internal). The Azure monitor exporter sees SpanKind.Client and tries to determine if it's an HTTP call, DB call, etc. In this case, it can't determine what the client call is and sets `Type` to N/A. 

There is an option to set an attribute called "az.namespace" to something like "OpenAI". If the azure monitor exporter sees SpanKind.Client and finds that attribute, it will set `Type` to the value. Not sure that's something you can do for just one exporter?

**Comment by nirga** [comment]
Thanks @drewby. Adding an attribute based on the exporter will be difficult since some people might be using it through a collector so we won't have a way of knowing. We might need to align on that as well as part of the semconv definition, and then maybe define that this is also a valid `SpanKind.Client`.

**Review by nirga — APPROVED** [review]

**Comment by nirga** [comment]
Merging this as is for now.

**Pull request merged**
