### PR TITLE
Adds general contributions

### PR DESCRIPTION
**Pull request by ankur0904**
This pull request adds a new contribution guide and updates the `mint.json` file to include a reference to this new guide. The most important changes include the addition of a detailed contribution guide in `openllmetry/contributing/general-guide.mdx` and the update to the `pages` array in `mint.json`.

Documentation updates:

* [`openllmetry/contributing/general-guide.mdx`](diffhunk://#diff-9520ee7da4e9936fff87dc5dfbf4fbb65ffd6e2468c3dfe09e72ea3e9fc8d401R1-R77): Added a comprehensive contribution guide detailing steps for forking, cloning, making changes, and submitting a pull request.
* [`mint.json`](diffhunk://#diff-f42b3e455b64bd6a447c4a0af574f6f957b5ad387d55c42c3a38d4473476b854L131-R132): Updated the `pages` array to include a reference to the new general contribution guide.

### CODE REVIEW

**Comment by nirga** [comment]
Thanks @ankur0904 - can we make it specific to us and not generic contributions? I think it will be more helpful

**Comment by ankur0904** [comment]
@nirga 
Done :)

**Comment by nirga** [comment]
@ankur0904 what I meant is that I think we may need a guide that is helping new contributors specifically with our repo, how to install, how to test, how to run... We don't really need a guide on how to open PRs as there are plenty of them

**Comment by ankur0904** [comment]
@nirga 
These things are mentioned here. 
https://github.com/traceloop/docs/blob/main/openllmetry/contributing/developing.mdx

**Comment by nirga** [comment]
Great @ankur0904, as a newcomer to our project - wanna try following them and say what you think is missing? :)

**Comment by nirga** [comment]
Closing this PR @ankur0904, feel free to reopen if you plan on working on this

**Pull request closed without merging**
